services:
  mysql:
    image: mysql:8
    container_name: safebase_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safebase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:16-alpine
    container_name: safebase_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: safebase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: safebase_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - postgres
    volumes:
      - ./backups:/app/backups

volumes:
  mysql_data:
  pg_data:
